name: Deploy Pennyworth Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  BASE_DOMAIN: ${{ secrets.BASE_DOMAIN }}
  ROUTE53_HOSTED_ZONE_ID: ${{ secrets.ROUTE53_HOSTED_ZONE_ID }}
  AWS_DEPLOY_ROLE_ARN: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
  STACK_NAME: ${{ secrets.STACK_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions
      - name: Build and package Lambda
        run: sam build
      - name: Deploy with SAM
        run: |
          sam deploy --stack-name $STACK_NAME \
            --capabilities CAPABILITY_IAM \
            --region $AWS_REGION \
            --parameter-overrides \
              DomainName=api.${BASE_DOMAIN} \
              HostedZoneId=$ROUTE53_HOSTED_ZONE_ID 