name: Deploy Pennyworth Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  BASE_DOMAIN: ${{ secrets.BASE_DOMAIN }}
  ROUTE53_HOSTED_ZONE_ID: ${{ secrets.ROUTE53_HOSTED_ZONE_ID }}
  AWS_DEPLOY_ROLE_ARN: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
  STACK_NAME: ${{ secrets.STACK_NAME }}
  ACM_CERTIFICATE_ARN: ${{ secrets.ACM_CERTIFICATE_ARN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build and package Lambda
        run: sam build
      - name: Deploy with SAM
        run: |
          sam deploy --stack-name $STACK_NAME \
            --capabilities CAPABILITY_IAM \
            --region $AWS_REGION \
            --resolve-s3 \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
              BaseDomain=$BASE_DOMAIN \
              AcmCertificateArn=$ACM_CERTIFICATE_ARN \
              Route53HostedZoneId=$ROUTE53_HOSTED_ZONE_ID 